In [1]:
import numpy as np


Parte 1: Numpy:
Para los ejercicios siguiente genere el código que considere 
para resolver el problema que se le plantea.

### 1) ¿Cuál es el tamaño en bytes de un array de 1000 
### elementos de tipo booleano?

In [2]:
arr1 = [True]*1000
import sys
print("el tamanio del arreglo es de:", sys.getsizeof(arr1),"bytes")

el tamanio del arreglo es de: 8056 bytes


### Cree un array cuyos elementos sean los enteros pares en 
### [1,100] y en orden decreciente. Muestre los 10 últimos 
### por pantalla.

In [3]:
arr2 = np.array(list(range(100,0,-2)))
print(arr2[-10:])

[20 18 16 14 12 10  8  6  4  2]


###  Dado el array
#### 2 4 5 6
#### 0 3 7 4
#### 8 8 5 2
#### 1 5 6 1
#### Seleccione con una instrucción el subarray de elementos
#### 0 3 7 4
#### Después, seleccione el subarray de elementos
#### 2 5
#### 8 5

In [4]:
arr3 = np.array([[2,4,5,6],[0,3,7,4],[8,8,5,2],[1,5,6,1]])
subarray1 = arr3[1,0:4]
subarray2 = arr3[0:3:2,0:4:3]
print(subarray1)
print(subarray2)

[0 3 7 4]
[[2 6]
 [8 2]]


### 4) Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], 
### obtenga la media aritmética de la diferencia (a-b).

In [5]:
a = np.array([1,4,2,7])
b = np.array([1,3,2,9])

diferencia = a - b

media = np.mean(diferencia)

print(media)

-0.25


### Tengo valores de cordenadas (x, y) en las columnas del array
### 1.33 4.5
### 30.0 10.7
### 70.2 0.5
### Agregue a este array las coordenadas (37.1, -3.6). 
### Muestre en pantalla las dimensiones del nuevo 
### array.

In [6]:
coordenadas = np.array([[1.33,4.5],[30.0,10.7],[70.2,0.5]])

nuevas_coordenadas = np.array ([[37.1,-3.6]])
coordenadas = np.concatenate((coordenadas,nuevas_coordenadas))
print(coordenadas.shape)
print(coordenadas)

(4, 2)
[[ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]
 [37.1  -3.6 ]]


### 6) Copie el array del ejercicio anterior. Traspóngalo (. 
### Agregue ahora dos nuevos pares de coordenadas: (10.8, 
### 3.0) y (35.8, 12.0).

In [8]:
coordenadas = np.array([[1.33, 4.5],[30.0, 10.7], [70.2, 0.5]])

# Agregar nuevas coordenadas
nuevas_coordenadas = np.array([[37.1, -3.6], [10.8, 3.0],  [35.8, 12.0]])

coordenadas = np.append(coordenadas, nuevas_coordenadas,axis = 0)

# Transponer el array
coordenadas_t = coordenadas.transpose()

print("Nuevo array:", coordenadas.shape)
print("Dimensiones transpuesto:", coordenadas_t.shape)
print(coordenadas)
print(coordenadas_t)




Nuevo array: (6, 2)
Dimensiones transpuesto: (2, 6)
[[ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]
 [37.1  -3.6 ]
 [10.8   3.  ]
 [35.8  12.  ]]
[[ 1.33 30.   70.2  37.1  10.8  35.8 ]
 [ 4.5  10.7   0.5  -3.6   3.   12.  ]]


# Parte 2: Exploración y Minería de Datos:

#### Con el dataset nucleospoblacion.csv adjunto al #### laboratorio, 
#### luego responda las siguientes preguntas usando pandas y 
#### matplotlib.
#### 1) ¿Cuántos Municipios tienen más de 100000 habitantes?.

In [9]:
import pandas as pd
df = pd.read_csv('NucleosPoblacion.csv')

In [12]:
municipios_100k = df[df['Poblacion']>100000]
cantidad_municipios=len(municipios_100k)
print(f"hay {cantidad_municipios} municipios con mas de 100,000 habitantes.")


hay 62 municipios con mas de 100,000 habitantes.
